#/**
#*
#* @File : makefile
#*
#*
#* @Synopsis : Makefile pour la compilation
#*
#**/
#

INCLUDE = ../include

all: PToN

PToN : 
		 gcc -o P2N64.run -I$(INCLUDE) -w -g -ansi -pedantic -std=c99 -O3 -Werror main.c

clean:
		clear; rm -rf P2N64.run
